// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvtovirtnnjdttwkwufc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2dG92aXJ0bm5qZHR0d2t3dWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjgxNTEsImV4cCI6MjA2MTc0NDE1MX0.jGoy5UY5g0i4bmrT7hHiudzLsPXCmWGdojIXB_Ie0a8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);